BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Originale" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"MAC"	TEXT,
	"ISPUB"	INTEGER,
	"RSSI"	INTEGER,
	"TIMESTAMP"	TEXT,
	"ROOT"	TEXT
);
CREATE TABLE IF NOT EXISTS "History" (
	"ID"	INTEGER,
	"MAC"	TEXT,
	"ISPUB"	INTEGER,
	"TIMESTAMP"	TEXT,
	"X"	INTEGER,
	"Y"	INTEGER
);
COMMIT;
